apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp
  namespace: sample-ns
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
