apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: application-ns
spec:
  type : ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
