pipeline {
    agent { label 'agent-linux' }

    environment {
        AZURE_CREDS = credentials('AZURE_CREDENTIALS')
    }

    parameters {
        choice(name: 'ACTION', choices: ['start', 'stop', 'status'], description: 'Action to perform')
        string(name: 'RESOURCE_GROUP', defaultValue: '', description: 'Azure Resource Group ')
        string(name: 'VM_NAME', defaultValue: '', description: 'Azure VM Name ')
    }

    stages {
        stage('Login to Azure') {
            steps {
                pwsh '''
                    # Set the Azure credentials environment variable
                    
                    $env:AZURE_CREDS_JSON = $env:AZURE_CREDS

                    # Use absolute path to the script
                    $scriptPath = "${env.WORKSPACE}powershell_scripts/login.ps1"

                    # Check if the script exists
                    if (Test-Path $scriptPath) {
                        Write-Host "Found login.ps1 at: $scriptPath"
                        & $scriptPath
                    } else {
                        Write-Host "login.ps1 not found at: $scriptPath"
                        exit 1
                    }
                '''
            }
        }

        stage('Run VM Action') {
            steps {
                pwsh """
                    ./manage-vm/manage-vm.ps1 `
                        -action '${params.ACTION}' `
                        -vmName '${params.VM_NAME}' `
                        -resourceGroup '${params.RESOURCE_GROUP}'
                """
            }
        }
    }
}
