pipeline {
    agent { label 'agent-linux' }

    environment {
        AZURE_CREDS = credentials('AZURE_CREDENTIALS')
    }

    stages {        

        stage('Login to Azure') {
            steps {
                pwsh '''
                    # Set the Azure credentials environment variable
                    $env:AZURE_CREDS_JSON = $env:AZURE_CREDS

                    # Use absolute path to the script
                
                    $scriptPath = "${env.WORKSPACE}/powershell_scripts/login.ps1"
                    & $scriptPath
                '''
            }
        }

        stage('Run Azure PowerShell') {
            steps {
                pwsh '''
                    # Run the script to list resource groups
                    $scriptPath = "${env.WORKSPACE}/powershell_scripts/list-resource-groups.ps1"
                    & $scriptPath
                '''
            }
        }
    }
}
