pipeline {
    agent { label 'agent-linux' }

    environment {
        AZURE_CREDS = credentials('AZURE_CREDENTIALS')
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the repository to make sure the .ps1 scripts are available
                checkout scm
            }
        }

        stage('Login to Azure') {
            steps {
                pwsh '''
                    # Set the Azure credentials environment variable
                    $env:AZURE_CREDS_JSON = $env:AZURE_CREDS

                    # Use absolute path to the script
                    $scriptPath = "${env.WORKSPACE}/login.ps1"
                    & $scriptPath
                '''
            }
        }

        stage('Run Azure PowerShell') {
            steps {
                pwsh '''
                    # Run the script to list resource groups
                    $scriptPath = "${env.WORKSPACE}/list-resource-groups.ps1"
                    & $scriptPath
                '''
            }
        }
    }
}
